### PR TITLE
Extension - Handle stereo audio from TeamSpeak (cherry pick)

### LINKED ISSUE #1237: Audio artifacts in TS channel with high(est) bitrate
Game and mods (from workshop) are latest versions at the moment. No ACE.
Teamspeak server version: 3.13.7 on Linux
client: 3.5.6
If ACRE's channel Audio codec is set to Opus Music with Quaility 10 for some clients sound is pitched down + crackling.
My input and output devices are all set to 24bit 48khz. I did not had any problems, but other client with 16 bit 44.1khz "Speakers" heard my voice with mentioned artifacts. No problems with Opus Voice Quality 10

I may add recorded example later.

### PR DESCRIPTION
**Pull request by PabstMirror**
fix #1237
Cherypick the stero fix from #1105
> acre just expects mono microphone data, but TS is capable of stereo
without the mono fix, everything was pitch shifted lower because the sound data is interleaved [left, right, left]

### CODE REVIEW

File: extensions/src/ACRE2Core/FilterPosition.cpp [hunk 1]
```diff
@@ -8,6 +8,7 @@
 
 #include <cmath>
 #pragma comment(lib, "x3daudio.lib")
+#pragma comment(lib, "xaudio2.lib")
```
Comment (PabstMirror) [inline extensions/src/ACRE2Core/FilterPosition.cpp:11]: not fully sure why this is now required, it's unrelated to pr but need to build on VS17.6

Comment (jonpas) [reply extensions/src/ACRE2Core/FilterPosition.cpp:11]: Interesting.

Comment (jonpas) [reply extensions/src/ACRE2Core/FilterPosition.cpp:11]: Didn't need that on VS17.5. :thinking:

Comment (PabstMirror) [reply extensions/src/ACRE2Core/FilterPosition.cpp:11]: error
```
2>ACRE2Core.lib(FilterPosition.obj) : error LNK2019: unresolved external symbol __imp_X3DAudioInitialize referenced in function "public: enum acre::Result __cdecl CFilterPosition::process(short *,int,int,unsigned int,class CSoundMixdownEffect *)" (?process@CFilterPosition@@QEAA?AW4Result@acre@@PEAFHHIPEAVCSoundMixdownEffect@@@Z)
2>ACRE2Core.lib(FilterPosition.obj) : error LNK2019: unresolved external symbol __imp_X3DAudioCalculate referenced in function "public: enum acre::Result __cdecl CFilterPosition::process(short *,int,int,unsigned int,class CSoundMixdownEffect *)" (?process@CFilterPosition@@QEAA?AW4Result@acre@@PEAFHHIPEAVCSoundMixdownEffect@@@Z)
```

it might just be something on my machine
we could just remove the line from the pr and let it build via github automation
or fix via cmake config, but we already had a existing `#pragma comment(lib`

Comment (jonpas) [reply extensions/src/ACRE2Core/FilterPosition.cpp:11]: It also builds with it for me, forgot to say that. So I am fine with leaving it in.

**Review by jonpas — APPROVED** [review]
